"""create plant catalog tables

Revision ID: 1cfb044337e5
Revises: c0529050b05c
Create Date: 2026-08-18 23:05:23.183146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cfb044337e5'
down_revision: Union[str, Sequence[str], None] = 'c0529050b05c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_categories',
    sa.Column('plant_category_uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('plant_category_uid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('plant_species',
    sa.Column('plant_species_uid', sa.UUID(), nullable=False),
    sa.Column('common_name', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ideal_temp_min_c', sa.Float(), nullable=True),
    sa.Column('ideal_temp_max_c', sa.Float(), nullable=True),
    sa.Column('ideal_humidity_min_percent', sa.Float(), nullable=True),
    sa.Column('ideal_humidity_max_percent', sa.Float(), nullable=True),
    sa.Column('ideal_soil_moisture_min_percent', sa.Float(), nullable=True),
    sa.Column('ideal_soil_moisture_max_percent', sa.Float(), nullable=True),
    sa.Column('sunlight_requirement', sa.String(length=32), nullable=False),
    sa.Column('watering_frequency_days', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("sunlight_requirement IN ('FULL_SUN', 'PARTIAL_SUN', 'PARTIAL_SHADE', 'FULL_SHADE')", name='ck_plant_species_sunlight_requirement'),
    sa.CheckConstraint('ideal_humidity_max_percent IS NULL OR ideal_humidity_max_percent BETWEEN 0 AND 100', name='ck_plant_species_humidity_max_range'),
    sa.CheckConstraint('ideal_humidity_min_percent IS NULL OR ideal_humidity_max_percent IS NULL OR ideal_humidity_min_percent <= ideal_humidity_max_percent', name='ck_plant_species_humidity_range'),
    sa.CheckConstraint('ideal_humidity_min_percent IS NULL OR ideal_humidity_min_percent BETWEEN 0 AND 100', name='ck_plant_species_humidity_min_range'),
    sa.CheckConstraint('ideal_soil_moisture_max_percent IS NULL OR ideal_soil_moisture_max_percent BETWEEN 0 AND 100', name='ck_plant_species_soil_moisture_max_range'),
    sa.CheckConstraint('ideal_soil_moisture_min_percent IS NULL OR ideal_soil_moisture_max_percent IS NULL OR ideal_soil_moisture_min_percent <= ideal_soil_moisture_max_percent', name='ck_plant_species_moisture_range'),
    sa.CheckConstraint('ideal_soil_moisture_min_percent IS NULL OR ideal_soil_moisture_min_percent BETWEEN 0 AND 100', name='ck_plant_species_soil_moisture_min_range'),
    sa.CheckConstraint('ideal_temp_min_c IS NULL OR ideal_temp_max_c IS NULL OR ideal_temp_min_c <= ideal_temp_max_c', name='ck_plant_species_temperature_range'),
    sa.CheckConstraint('watering_frequency_days > 0', name='ck_plant_species_watering_frequency_positive'),
    sa.PrimaryKeyConstraint('plant_species_uid'),
    sa.UniqueConstraint('scientific_name')
    )
    op.create_table('plant_care_guides',
    sa.Column('plant_care_guide_uid', sa.UUID(), nullable=False),
    sa.Column('plant_species_uid', sa.UUID(), nullable=False),
    sa.Column('watering_guide', sa.Text(), nullable=False),
    sa.Column('fertilizer_guide', sa.Text(), nullable=True),
    sa.Column('pruning_guide', sa.Text(), nullable=True),
    sa.Column('common_problems', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_species_uid'], ['plant_species.plant_species_uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plant_care_guide_uid'),
    sa.UniqueConstraint('plant_species_uid')
    )
    op.create_table('plant_species_categories',
    sa.Column('plant_species_uid', sa.UUID(), nullable=False),
    sa.Column('plant_category_uid', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_category_uid'], ['plant_categories.plant_category_uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plant_species_uid'], ['plant_species.plant_species_uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plant_species_uid', 'plant_category_uid')
    )
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=56),
               existing_nullable=False)
    op.alter_column('roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('verification_tokens', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('verification_tokens', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_tokens', 'used_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('verification_tokens', 'revoked_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('roles', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=56),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_table('plant_species_categories')
    op.drop_table('plant_care_guides')
    op.drop_table('plant_species')
    op.drop_table('plant_categories')
    # ### end Alembic commands ###
