"""add server defaults for plant catalog UUIDs

Revision ID: 66f58a857a9a
Revises: 1cfb044337e5
Create Date: 2026-08-18 23:16:30.673155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '66f58a857a9a'
down_revision: Union[str, Sequence[str], None] = '1cfb044337e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant_care_guides', 'plant_care_guide_uid',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('plant_categories', 'plant_category_uid',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('plant_species', 'plant_species_uid',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant_species', 'plant_species_uid',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('plant_categories', 'plant_category_uid',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('plant_care_guides', 'plant_care_guide_uid',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
