"""token verification changes

Revision ID: 77123e026c2c
Revises: b7bb9ccaeb53
Create Date: 2026-08-10 09:14:25.269106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77123e026c2c'
down_revision: Union[str, Sequence[str], None] = 'b7bb9ccaeb53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_tokens', sa.Column('used_at', sa.DateTime(), nullable=True))
    op.alter_column('verification_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('verification_tokens', 'used_at')
    # ### end Alembic commands ###
